### ISSUE TITLE
大神不会写代码的奶爸请教一下如何运行（使用）？

### ISSUE THREAD

**Issue by xiaonibakeji** [sunzsh/pinyin-vue#1]
请问一下应该如何使用你的代码，怎么才能让它运行起来，不胜感激

**Comment by sunzsh** [comment]
直接访问这个链接就可以用：https://sunzsh.github.io/pinyin/

**Comment by xiaonibakeji** [comment]
> 直接访问这个链接就可以用：https://sunzsh.github.io/pinyin
感谢，非常棒，。要是能加上汉字和读音就更好了。同时可以识字了。
